class  AppError extends Error {
  constructor(message, statusCode){
    super(message);
    this.statusCode = statusCode;
    this.status = `${statusCode}`.startsWith(4) ? 'Fail' : 'Error';
    this.isOperational = true; //just writing to say this is generated by us

    // get the line number of the error
    Error.captureStackTrace(this, this.constructor);
  }

}


module.exports = AppError;